### ISSUE TITLE
Why not go https-only?

### ISSUE THREAD

**Issue by aardbol** [GrapheneOS/releases.grapheneos.org#19]
Looking at your nginx configs, they all have an http config added to them which makes them vulnerable to a MITM attack. Why not go https-only and do DNS based validation for your certificates?

**Comment by thestinger** [comment]
We use the CAA Account URI feature to cryptographically secure the HTTP validation method. You can see this here:

https://github.com/GrapheneOS/ns1.grapheneos.org/blob/main/zones.yaml

This avoids us having to expose additional attack surface from our authoritative DNS servers to provide dynamic configuration. The HTTP validation is authenticated and not vulnerable to any form of MITM attack. We prefer this over adding attack surface and complexity to the authoritative DNS servers.

The HTTP service for nearly all the services solely exists to redirect bots from HTTP to HTTPS along with providing domain validation support with account binding. For our network servers, HTTP is needed because there are both HTTP and HTTPS connectivity checks since HTTP is purposely used to detect interception by a captive portal to trigger the special UI for handling captive portals even with an always-on VPN enabled.

Aside from the HTTP connectivity checks, everything we have only uses HTTPS and has no need for the HTTP redirects. Lots of bots connect to the HTTP services and get redirected to the HTTP services though. They're still going to be trying to connect without having an HTTP service but we won't be able to provide them the redirect.

We have HSTS with preloading for all the regular domains. The only exception are grapheneos.network and grapheneos.online exclusively used for connectivity checks because they need to allow using HTTP from a browser with HSTS preload lists for captive portal handling. Those are a special case where HTTP is actually needed to permit the captive portal to MITM the connection. That's how captive portals work and the OS needs special support for them because in practice nothing else uses HTTP anymore so captive portals cannot ever intercept anything to show their UI without the OS going out of the way to enable.

**Comment by thestinger** [comment]
It wouldn't be secure to simply switch to DNS-based certificate issuance without using the CAA Method Binding feature to permit only DNS-based issuance. HTTP-based issuance could still be triggered by anyone without having actual authentication. Not having HTTP listening wouldn't change that someone able to MITM the requests made from multiple perspectives by Let's Encryption could get valid certificates issued. Method Binding and Account URI were standardized together and generally one wouldn't be supported without the other. HTTP-based validation with authentication is just what we prefer since we use the method based on putting files into the .well-known directory so it doesn't involve any dynamic configuration. Additionally, it's easy enough for us to support with multiple instances by having the secondary instances redirect requests for this to the main instance handling certificate issuance. We can't do issuance separately on each instance because we could / would hit the rate limits so it inherently needs to have sync from the main instance. We could make this lower privileged but it's painful to make certbot run as non-root even though it clearly doesn't need it. We haven't bothered to do this yet because of how painful and error prone it would be to keep working.
